//coverage:ignore file

// Code generated by MockGen. DO NOT EDIT.
// Source: transformer/transformer.go

// Package transformer is a generated GoMock package.
package transformer

import (
	data "github.com/companieshouse/payment-reconciliation-consumer/data"
	models "github.com/companieshouse/payment-reconciliation-consumer/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockTransformer is a mock of Transformer interface
type MockTransformer struct {
	ctrl     *gomock.Controller
	recorder *MockTransformerMockRecorder
}

// MockTransformerMockRecorder is the mock recorder for MockTransformer
type MockTransformerMockRecorder struct {
	mock *MockTransformer
}

// NewMockTransformer creates a new mock instance
func NewMockTransformer(ctrl *gomock.Controller) *MockTransformer {
	mock := &MockTransformer{ctrl: ctrl}
	mock.recorder = &MockTransformerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTransformer) EXPECT() *MockTransformerMockRecorder {
	return m.recorder
}

// GetEshuResources mocks base method
func (m *MockTransformer) GetEshuResources(payment data.PaymentResponse, paymentDetails data.PaymentDetailsResponse, paymentId string) ([]models.EshuResourceDao, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEshuResources", payment, paymentDetails, paymentId)
	ret0, _ := ret[0].([]models.EshuResourceDao)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEshuResources indicates an expected call of GetEshuResources
func (mr *MockTransformerMockRecorder) GetEshuResources(payment, paymentDetails, paymentId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEshuResources", reflect.TypeOf((*MockTransformer)(nil).GetEshuResources), payment, paymentDetails, paymentId)
}

// GetTransactionResources mocks base method
func (m *MockTransformer) GetTransactionResources(payment data.PaymentResponse, paymentDetails data.PaymentDetailsResponse, paymentId string) ([]models.PaymentTransactionsResourceDao, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionResources", payment, paymentDetails, paymentId)
	ret0, _ := ret[0].([]models.PaymentTransactionsResourceDao)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionResources indicates an expected call of GetTransactionResources
func (mr *MockTransformerMockRecorder) GetTransactionResources(payment, paymentDetails, paymentId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionResources", reflect.TypeOf((*MockTransformer)(nil).GetTransactionResources), payment, paymentDetails, paymentId)
}

// GetRefundResource mocks base method
func (m *MockTransformer) GetRefundResource(payment data.PaymentResponse, refund data.RefundResource, paymentId string) (models.RefundResourceDao, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefundResource", payment, refund, paymentId)
	ret0, _ := ret[0].(models.RefundResourceDao)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefundResource indicates an expected call of GetRefundResource
func (mr *MockTransformerMockRecorder) GetRefundResource(payment, refund, paymentId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefundResource", reflect.TypeOf((*MockTransformer)(nil).GetRefundResource), payment, refund, paymentId)
}
